Section "InputClass"
    Identifier "Chromebook Touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "NaturalScrolling" "true"
    Option "Tapping" "true"
    Option "TappingButtonMap" "lrm"
    Option "PalmDetection" "true"
    Option "PalmMinWidth" "8"
    Option "PalmMinZ" "100"
    Option "DisableWhileTyping" "true"
    Option "ClickMethod" "clickfinger"
EndSection
